services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4568:4566' # LocalStack Gateway
      - '4710-4759:4710-4759' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns
      LOCALSTACK_HOST: 127.0.0.1
      EXTERNAL_SERVICE_PORTS_START: 4710
      EXTERNAL_SERVICE_PORTS_END: 4759
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - ahwr-local

  mongodb:
    image: mongo:7.0.28
    networks:
      - ahwr-local
    ports:
      - '27020:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  ################################################################################

  ahwr-document-generator-backend:
    build:
      context: .
      target: development
    ports:
      - '3008:3001'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      AWS_ENDPOINT_URL: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
      USE_PRETTY_PRINT: true
      DOCUMENT_BUCKET_NAME: ahwr-documents
      DOCUMENT_REQUEST_QUEUE_URL: "http://sqs.eu-west-2.127.0.0.1:4566/000000000000/ahwr_document_generator_queue"
      DOCUMENT_CREATED_TOPIC_ARN: "arn:aws:sns:eu-west-2:000000000000:ahwr_document_created"
      APPLY_SERVICE_URI: "http://localhost:3002/sign-in"
      TERMS_AND_CONDITIONS_URL: "https://www.gov.uk/government/publications/get-funding-to-improve-animal-health-and-welfare-terms-and-conditions"
      BACKOFFICE_UI_API_KEY: ${BACKOFFICE_UI_API_KEY:-446dcdbe-e02c-4d16-a266-001bbbd5f089}
      APPLICATION_BACKEND_API_KEY: ${APPLICATION_BACKEND_API_KEY:-fab78725-3037-45ed-ad2e-28cd86e70ff8}
    networks:
      - ahwr-local
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

################################################################################

volumes:
  mongodb-data:

networks:
  ahwr-local:
    external: true
    name: ahwr-local
